### ISSUE TITLE
time lag between takepicture and takepicturehandler

### ISSUE THREAD

**Issue by 9rohand** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#132]
i tested the app and i found a considerable lag between when the takepicture ends and when takepicturehandler starts. It is about 4-5 seconds. This time lag is huge as i do processing on takepicturehandler that takes another 5 seconds. Is there anyway to reduce this timelag?

**Comment by Giriton** [comment]
There may be long delay due to the Android itself and camera init. To some cameras it takes about 1 second to init and about 1 second to adapt to light etc.

We have workerounded that by leaving camera on, streaming video continuously. We called .hide() to hide the preview box, but camera continues running in background. Screenshot is then performed immediatelly.

Note: at the beginning you need to leave the camera shown for a short moment (1 second) to init properly, then you can hide it.

Note2: just when performing screenshot, we call .show() method to show the preview box. Then we take screenshot and then hide it again. Not sure whether it is necessarry to re-show and re-hide it to make it work, that is just the way we have it implemented.

Hope it helps :-)

**Comment by 9rohand** [comment]
HI, 
I am taking about post init, focus and adjusting to light. When all those adjustmnets are done (i.e. after i have waited for those inits and all to load up), I then run takepicture function. Image is immediately saved but the takepicturehandler function is triggered after 5 seconds everytime. 

Snap is quick but the handler that runs after snap is not..any workaround for that?

**Comment by erperejildo** [comment]
Try with small sizes and using fastclick.js as well

**Comment by 9rohand** [comment]
with small sizes of startcamera it is quick. How can i switch dynamically width and height of startcamera before and after takepicture function?

**Comment by erperejildo** [comment]
Can you try with new version? A lot of new changes have been merged
