### ISSUE TITLE
save photo on gallery

### ISSUE THREAD

**Issue by jedofus** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#268]
Hi, 
i want to save photo in my app after i take photo.
how can i do this ? (Android & iOS)

**Comment by HartHerbert** [comment]
you can use the file plugin to accomplish this. This plugin is not here to save taken pictures on the device, because this would need a permission more on the device. So you have to do this on your own.you can use the cordova-plugin-file to save base64 strings as jpg or png on the device, just look it up.

**Comment by jedofus** [comment]
thank you for your response !
