### ISSUE TITLE
No onBackButton method found

### ISSUE THREAD

**Issue by moonlitnighta** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#388]
Uncaught TypeError: CameraPreview.onBackButton is not a function！

**Comment by Choppel** [comment]
Hi moonlitnighta,
it seems this function is not implemented in the checked out version 0.9.0. Take a look at your local www/CameraPreview.js in the plugin directory. The function is missing there.
However, it exists in the master repo on github. So there seems to be something weird going on with 0.9.0.

Nonetheless i'd recommend using a separate backbutton plugin (cordova-plugin-backbutton) as IMO it should not be part of cordova-plugin-camera-preview at all.

Or maybe the function will get fixed in the next version.

regards Choppel

**Comment by westonganger** [comment]
If its fixed in master. We dont support old versions. Closing this issue.
