### ISSUE TITLE
Keep live preview on taking photo

### ISSUE THREAD

**Issue by xeweb** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#445]
Is there a way to keep the preview running while taking a photo? I want to take multiple photos in a small amount of time, but when the first photo is shot the camera preview freezes to that image. The image are taken correctly tought. Running it on Android.

**Comment by Choppel** [comment]
Hi @xeweb 
that depends on your device.
I have a Samsung Xcover 3 SM-G388F. The lag is about 500ms to 1000ms.
On a Samsung S7 and on a recent iPad there is no lag. The camera is very fast.
It may be, because the android part of this plugin uses a deprecated camera api. So I think you will have to live with that.
