### ISSUE TITLE
PR: tapFocus + toBack

### ISSUE THREAD

**Issue by xGeorge** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#466]
On Android its an easy task with a simple if statement and a new property to force the setupTouchAndBackButton its done, but in iOS we will probably will need to propagate the event to the upper UIView(webview) with the CGPoint

**Comment by Bengejd** [comment]
This is pretty easily done, and it's already built into the functionality (mostly). 

I created a `div` within the template, assigned it a set height (so that it doesn't overlap my buttons at the bottom of the page), and then set the focus to the x,y events of the `(tap)` event.

**The template.**
```
<div (tap)="focusCamera($event)" class="box background"></div>
``` 

**Find the screen height in your constructor.**
```
    this.screenHeight = this.platform.height();
```

**The functions to focus the camera:**

**Receives the tap $event**
```

focusCamera($event) {
    if($event.center.y < (this.screenHeight * 0.8)) {
      log.info('CameraPreview.ts:: Focus within area');
      log.info('CameraPreview.ts:: FocusArea: ', $event.center.x, ' ', $event.center.y);
      this.cameraPreview.tapToFocus($event.center.x, $event.center.y);
    }
```
**Focuses the camera.**
```

tapToFocus(x,y) {
    return this.cameraPreview.tapToFocus(x,y)
    .catch(err => {
      log.error('CameraPreviewService: An error occured while focusing the camera: ', err);
    });
  }
```

**The scss file**
```
  .box {
    position: absolute;
    width:100vw;
    height:80vh;
  }

  .background {
    background: transparent;
  }
```
