### ISSUE TITLE
toBack is not working when cordova-plugin-googlemaps is added with

### ISSUE THREAD

**Issue by aliraouf20390** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#496]
I'm facing this problem with camera preview plugin. Actually our app requires this feature of applying filters to captured image. It works fine, but one of our core feature requires native google maps too.
With google maps plugin camera features breaks. Camera comes in-front of html and main feature turns useless.
I tried some solution like this one:

this file : platforms/android/src/plugin/google/maps/MyPluginLayout.java
Commenting this line:
 //frontLayer.addView(browserView);
And adding this code: root.addView(browserView);
below  root.addView(this);

But this solution breaks maps feature, google maps gets untouchable and nothings works with google maps then.
Please let me know if there's some solution to this problem.
Thanks in advance

**Comment by littork** [comment]
+1, I also have this exact issue.

**Comment by littork** [comment]
Any update on this? I am also having this issue

**Comment by littork** [comment]
So I finally managed to fix it by modifying the source for Camera Preview. Cordova Google Maps adjusts the hierarchy of the webview by placing it down two steps. This means that in order to achieve the same access while Google Maps is operating, Camera Preview must adjust the frame of reference used in its toBack handling.

I modified platforms/android/app/src/main/java/com/cordovaplugincamerapreview/CameraPreview.java:
![The modifications](https://user-images.githubusercontent.com/31424592/49840387-6821a500-fd70-11e8-9f11-8fb30b1da2f3.PNG)

By referencing the parent of the parent for each access, toBack functionality can be restored.

**Comment by KiwiKilian** [comment]
I'm also seeing this problem using Google Maps and Camera Preview Plugin together on Android. iOS is totatlly fine. Did somebody test this fixed or [this similar solution](https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/451#issuecomment-382719409) without the Google Maps Plugin? Will see to find some time to setup two test apps with and without the Google Maps Plugin. Would be awesome to make this fix permanent.
