### ISSUE TITLE
toBack not working on android 8.1

### ISSUE THREAD

**Issue by rhiroshi** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#497]
Hello.
I'm using camera preview covering the whole page. I added ionic's FAB (Floating Action Button) to take photos and exiting the page, so i use the toBack options so the camera preview goes behing the html.
It worked fine on android 4.1.2, 6.x(i dont remember exactly which one) and 7.1. My phone recently updated to 8.1 and when i tried to run the project on that phone, the FABs were missing (when the page as opened, the buttons flashed but then disappeared, as if they went under the camera preview). I thought i messed with something so i tried running on a android 4.1.2 device and it was fine.
Is it a bug or do i need some extra css on 8.1 devices?

Thanks

**Comment by BeatriceThalo** [comment]
`((ViewGroup)webView.getView()).bringToFront();`  doesn't seem to be working

**Comment by BeatriceThalo** [comment]
I found an older commit which detaches the webview from whatever parent cordova had used and then attaches the webview as a child of the camera feed's parent (so that they are siblings), which works. See my fork's (admittedly untidy) branch (also with setPreviewPosition for the xy) [here](https://github.com/BeatriceThalo/cordova-plugin-camera-preview/tree/xy-position)

**Comment by rhiroshi** [comment]
Fixed by updating plugin to v4.20
