### ISSUE TITLE
this plugin not have flash light support in camara

### ISSUE THREAD

**Issue by ejazmafat999** [cordova-plugin-camera-preview/cordova-plugin-camera-preview#78]
i want this plugin with flash liaght facility

thank you

**Comment by 526avijitgupta** [comment]
+1

**Comment by samsadtler** [comment]
+1

**Comment by ejazmafat999** [comment]
i never seen flashed during taking picture ,@samsadtler  u r so luckky to seen .

plz help me to attach flash light in this plugin

**Comment by troyberg** [comment]
What I've noticed (on both iphone 6s and 5s), is that the plugin inherits what ever flash setting your native camera app is currently using. Try setting your native camera app to "on" rather than "auto" or "off", then see what happens. Of course, there's probably a good chance that not every device will behave like this.

**Comment by julitroalves** [comment]
+1 I have some issue with this plugin. I want to be able to enable and disable flash light via cordova api.

**Comment by erperejildo** [comment]
Available for Android and waiting PR for IOS:
https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview/issues/167
